name: Publish Docker image

on:
  push:
    brances: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest # what is going to run the image
    steps:
      - name: check out the repo # To switch to a specific branch, use the git checkout command
        uses: actions/checkout@v3

      - name: log in to Docker Hub
        uses: 
        with:


name: Build Docker image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and tag image
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        run: docker build -t ${{ github.repository }}:$COMMIT_SHA -f path/to/Dockerfile .

        - name: Build and tag image
          run: |
            COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
            docker build -t ${{ github.repository }}:$COMMIT_SHA -f path/to/Dockerfile .   

        - name: Get version
          run: |
            export VERSION=$(cat version.txt)
            echo "Version: $VERSION"    

        - name: Build and tag image
          run: docker build -t ${{ github.repository }}:$VERSION -f path/to/Dockerfile .