name: Publish Docker image # name of the workflow  

on:
  push:
    branches: 
      - 'master' # workflow run whenever there is a push to master branch

jobs:
  build-push: # job name 
    name: build the image 
    runs-on: ubuntu-latest #  type of runner that will execute the job
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # enabling advanced build features

      - name: log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short commit SHA # to know what was the state of the code at a certain point in time
        id: vars
        run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
        
      - name: Build and tag image # build the Docker image and tags it with the short commit SHA
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-web-app:${{ env.COMMIT_SHA }} .

      - name: Push Docker image # push the tagged image to Docker Hub with the commit sha
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-web-app:${{ env.COMMIT_SHA }} 
