name: Publish Docker image # name of the workflow  

on:
  push:
    branches: 
      - master # workflow run whenever there is a push to master branch

jobs:
  build-push:
    name: build the image # job name
    runs-on: ubuntu-latest #  type of runner that will execute the job (github hosted runner)
    permissions:
      contents: read
      packages: write
      id-token: write
    
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # enabling advanced build features

      - name: log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short commit SHA # to know what was the state of the code at a certain point in time
        id: vars
        run: echo "COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and tag image
        run: |
          docker buildx build \
            --file "C:/Users/maye/Documents/My_learning/CICD_Lab/Dockerfile" \
            --tag ${{ secrets.DOCKER_USERNAME }}/my-web-app:${{ env.COMMIT_SHA }} .

      - name: Push Docker image # push the tagged image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-web-app:${{ env.COMMIT_SHA }} 
